name: OFRP Builder
on:
  workflow_dispatch:
    inputs:
      BRANCH:
        description: 'Branch'
        required: true
        default: '12.1'
        type: choice
        options:
        - '11.0'
        - '12.1'
      DEVICE_TREE_URL:
        description: 'Device Tree URL'
        required: true
        default: 'https://github.com/VThang51/android_device_samsung_a13'
      DEVICE_TREE_BRANCH:
        description: 'Device Tree Branch'
        required: true
        default: 'master'
      DEVICE_PATH:
        description: 'Device Path'
        required: true
        default: 'device/samsung/a13x'
      DEVICE_NAME:
        description: 'Device Name'
        required: true
        default: 'a13x'
      MAKEFILE_NAME:
        description: 'Makefile Name'
        required: true
        default: 'twrp_a13x'
      ADD_SCRIPT:
        description: 'Add Script'
        required: false
      BUILD_TARGET:
        description: 'Build Target'
        required: true
        default: 'recovery'
        type: choice
        options:
          - 'recovery'
          - 'adbd recovery'
          - 'boot'
          - 'adbd boot'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Cleanup
        uses: rokibhasansagar/slimhub_actions@main

      - name: Prepare the build environment
        run: |
          wget -qO - https://github.com/VThang51/Recovery-Builder-Online/raw/main/sh/sudo.sh | bash
          cd ~
          git clone https://gitlab.com/OrangeFox/misc/scripts
          cd scripts
          sudo bash setup/android_build_env.sh
          sudo bash setup/install_android_sdk.sh
        continue-on-error: true
        
      - name: Sync OrangeFox sources and minimal manifest
        run: |
          mkdir ~/OrangeFox_sync
          cd ~/OrangeFox_sync
          git clone https://gitlab.com/OrangeFox/sync.git
          cd ~/OrangeFox_sync/sync/
          ./orangefox_sync.sh --branch ${{ inputs.BRANCH }} --path ~/fox_${{ inputs.BRANCH }}

      - name: Place device trees and kernel
        run: |
          cd ~/fox_${{ inputs.BRANCH }}
          git clone -b ${{ inputs.DEVICE_TREE_BRANCH }} ${{ inputs.DEVICE_TREE_URL }} ${{ inputs.DEVICE_PATH }}
          
      - name: Build it
        run: |
          cd ~/OrangeFox
          chmod 777 build/envsetup.sh
          source build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
          export LC_ALL="C"
          ${{ inputs.ADD_SCRIPT }}
          lunch ${{ inputs.MAKEFILE_NAME }}-eng
          mka ${{ inputs.BUILD_TARGET }}image

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ inputs.DEVICE_NAME }}
          tag_name: ${{ github.run_id }}
          body: |
            Manifest: ${{ inputs.BRANCH }}
            Device: ${{ inputs.DEVICE_NAME }}
            Target: ${{ inputs.BUILD_TARGET }}.img
          files: ofrp/out/target/product/${{ inputs.DEVICE_NAME }}/OrangeFox-unofficial-${{ inputs.DEVICE_NAME }}.img
