name: Build OFRP for Samsung Galaxy A13 (SM-A135F / Exynos 850)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Init the System
         uses: actions/checkout@master

       - name: Install the necessary packages
         run: |
             wget -qO - https://github.com/VThang51/Recovery-Builder-Online/raw/main/General/sudo.sh | bash

       - name: Prepare the build environment
         run: |
             cd ~
             git clone https://gitlab.com/VThang51/scripts
             cd scripts
             sudo bash setup/android_build_env.sh
             sudo bash setup/install_android_sdk.sh
             
       - name: Sync OrangeFox sources and minimal manifest
         run: |
             mkdir ~/OrangeFox_sync
             cd ~/OrangeFox_sync
             git clone https://gitlab.com/OrangeFox/sync.git
             cd ~/OrangeFox_sync/sync/
             ./orangefox_sync.sh --branch 12.1 --path ~/fox_12.1
              
       - name: Place device trees and kernel
         run: |
             cd ~/fox_12.1
             git clone -b master https://github.com/corsicanu/android_device_samsung_a13.git device/samsung/a13x

       - name: Build it
         run: |
             cd ~/OrangeFox # (or whichever directory has the synced manifest)
             source build/envsetup.sh
             export ALLOW_MISSING_DEPENDENCIES=true
             export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
             export LC_ALL="C"
             export OF_AB_DEVICE=1
             export OF_USE_MAGISKBOOT_FOR_ALL_PATCHES=1
             lunch twrp_<device>-eng && mka adbd bootimage

       - name: Release recovery
         uses: softprops/action-gh-release@v1
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
          tag_name: ${{ github.run_id }}
          name: OFRP-a13x
          files: out/target/product/a13x/OrangeFox-unofficial-a13x.img
