name: Building "OrangeFox Recovery Project" Version 1.1

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  workflow_dispatch:

env:
  MANIFEST: 
  DEVICE: a13x
  DT_LINK: https://github.com/corsicanu/android_device_samsung_a13
  DT_PATH: device/samsung/a13x
  TARGET: recoveryimage
  TZ: Asia/Vietnam

jobs:
  build:
    runs-on: debian-10

    steps:
       - name: Checkout
         uses: actions/checkout@master
         

       - name: Initializing environment
         run: |
              sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
              docker rmi `docker images -q`
              sudo apt-get remove account-plugin-facebook account-plugin-flickr account-plugin-jabber account-plugin-salut account-plugin-twitter account-plugin-windows-live account-plugin-yahoo aisleriot brltty duplicity empathy empathy-common example-content gnome-accessibility-themes gnome-contacts gnome-mahjongg gnome-mines gnome-orca gnome-screensaver gnome-sudoku gnome-video-effects gnomine landscape-common libreoffice-avmedia-backend-gstreamer libreoffice-base-core libreoffice-calc libreoffice-common libreoffice-core libreoffice-draw libreoffice-gnome libreoffice-gtk libreoffice-impress libreoffice-math libreoffice-ogltrans libreoffice-pdfimport libreoffice-style-galaxy libreoffice-style-human libreoffice-writer libsane libsane-common mcp-account-manager-uoa python3-uno rhythmbox rhythmbox-plugins rhythmbox-plugin-zeitgeist sane-utils shotwell shotwell-common telepathy-gabble telepathy-haze telepathy-idle telepathy-indicator telepathy-logger telepathy-mission-control-5 telepathy-salut totem totem-common totem-plugins printer-driver-brlaser printer-driver-foo2zjs printer-driver-foo2zjs-common printer-driver-m2300w printer-driver-ptouch printer-driver-splix
              sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* 
              sudo -E apt-get clean
              sudo -E apt-get -qq update
              sudo -E apt-get -qq upgrade
              sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev repo rsync flex curl  bison aria2 python2.7 python-pip
              sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
              sudo chmod a+rx /usr/local/bin/repo
              
       - name: Prepare the build environment
         run: |
              cd ~
              git clone https://gitlab.com/OrangeFox/misc/scripts
              cd scripts
              sudo bash setup/android_build_env.sh
              sudo bash setup/install_android_sdk.sh
            
       - name: Sync OrangeFox sources and minimal manifest
         run: |
              mkdir ~/OrangeFox_sync
              cd ~/OrangeFox_sync
              git clone https://gitlab.com/OrangeFox/sync.git
              cd ~/OrangeFox_sync/sync/
              ./orangefox_sync.sh --branch 12.1 --path ~/fox_12.1

       - name: Place device trees and kernel
         run: |
              cd ~/fox_12.1 # (or whichever directory hosts the synced manifest)
              git clone -b master https://github.com/corsicanu/android_device_samsung_a13.git device/samsung/a13x

       - name: Build
         run: |
              cd ~/OrangeFox
                  source build/envsetup.sh
                export ALLOW_MISSING_DEPENDENCIES=true
                export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
                export LC_ALL="C"
                export OF_AB_DEVICE=1
                export OF_USE_MAGISKBOOT_FOR_ALL_PATCHES=1
                lunch twrp_a13x-eng && mka adbd bootimage
             
       - name: Release Recovery Image
         uses: softprops/action-gh-release@v1
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
          tag_name: OFRP_12.1
          name: OFRP-a13x
          files: | 
                 out/target/product/a13x/OrangeFox-unofficial-a13x.img
