name: OrangeFox-RP Builder
on:
  workflow_dispatch:
    inputs:
      BRANCH:
        description: 'Branch'
        required: true
        default: '12.1'
        type: choice
        options:
        - '11.0'
        - '12.1'
      DEVICE_TREE_URL:
        description: 'Device Tree URL'
        required: true
        default: 'https://github.com/VThang51/android_device_samsung_a13'
      DEVICE_TREE_BRANCH:
        description: 'Device Tree Branch'
        required: true
        default: 'master'
      BRAND:
        description: 'Brand'
        required: true
        default: 'samsung'
      DEVICE_CODE:
        description: 'Device Code'
        required: true
        default: 'a13x'
      MAKEFILE_TYPE:
        description: 'Makefile Type'
        required: true
        default: 'twrp'
        type: choice
        options:
          - 'omni'
          - 'twrp'
      ADD_EXPORT:
        description: 'Add "export"'
        required: false
      BUILD_TARGET:
        description: 'Build Target'
        required: true
        default: 'recovery'
        type: choice
        options:
          - 'recovery'
          - 'adbd recovery'
          - 'boot'
          - 'adbd boot'
jobs:
  OrangeFox-Recovery-Project:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Free up Space
        uses: rokibhasansagar/slimhub_actions@main

      - name: Remove and Install the necessary Packages
        run: |
          bash sh/sudo.sh
          cd ~
          git clone https://gitlab.com/OrangeFox/misc/scripts
          cd scripts
          sudo bash setup/android_build_env.sh
          sudo bash setup/install_android_sdk.sh
        continue-on-error: true
        
      - name: Sync Minimal Manifest
        run: |
          mkdir ofrp
          cd ofrp
          git clone https://gitlab.com/OrangeFox/sync.git

      - name: Sync Source
        run: |
          cd ofrp
          chmod 777 sync/orangefox_sync.sh
          sudo ./sync/orangefox_sync.sh --branch ${{ inputs.BRANCH }} --path /complie

      - name: Clone Device Tree
        run: |
          cd ofrp/complie
          git clone -b ${{ inputs.DEVICE_TREE_BRANCH }} ${{ inputs.DEVICE_TREE_URL }} device/${{ inputs.BRAND }}/${{ inputs.DEVICE_CODE }}

      - name: Find file
        run: |
          cd ofrp
          find . -name *.sh
          
      - name: Compile Custom Recovery 
        run: |
          cd ofrp/complie
          chmod 777 build/envsetup.sh
          source build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
          export LC_ALL="C"
          ${{ inputs.ADD_EXPORT }}
          lunch ${{ inputs.MAKEFILE_TYPE }}_${{ inputs.DEVICE_CODE }}-eng
          mka ${{ inputs.BUILD_TARGET }}image

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Custom Recovery for ${{ inputs.DEVICE_CODE }}
          tag_name: ${{ inputs.BRANCH }}
          body: |
            Device: ${{ inputs.DEVICE_CODE }}
            Type: OrangeFox Recovery Project (OFRP)
            Target: ${{ inputs.BUILD_TARGET }}
          files: ofrp/out/target/product/${{ inputs.DEVICE_NAME }}/OrangeFox-unofficial-${{ inputs.DEVICE_NAME }}.img
