name: PitchBlack-RP Builder
on:
  workflow_dispatch:
    inputs:
      MANIFEST_BRANCH:
        description: 'Manifest Branch'
        required: true
        default: 'android-12.1'
        type: choice
        options:
          - 'twrp-6.0'
          - 'android-6.0'
          - 'twrp-7.1'
          - 'android-7.1'
          - 'twrp-8.1'
          - 'android-8.1'
          - 'android-9.0'
          - 'android-10.0'
          - 'android-11.0'
          - 'android-12.1'
      DEVICE_TREE_URL:
        description: 'Device Tree URL'
        required: true
        default: 'https://github.com/VThang51/android_device_samsung_a13'
      DEVICE_TREE_BRANCH:
        description: 'Device Tree Branch'
        required: true
        default: 'master'
      BRAND:
        description: 'Brand'
        required: true
        default: 'samsung'
      DEVICE_CODE:
        description: 'Device Code'
        required: true
        default: 'a13x'
      MAKEFILE_TYPE:
        description: 'Makefile Type'
        required: true
        default: 'twrp'
        type: choice
        options:
          - 'omni'
          - 'twrp'
      ADD_EXPORT:
        description: 'Add "export"'
        required: false
      BUILD_TARGET:
        description: 'Build Target'
        required: true
        default: 'recovery'
        type: choice
        options:
          - 'recovery'
          - 'boot'
          - 'vendorboot'
jobs:
  TeamWin-Recovery-Project:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Free up space
        uses: rokibhasansagar/slimhub_actions@main

      - name: Set up the Compilation environment
        run: bash sh/sudo.sh

      - name: Git Config
        run: |
          rm -rf pbrp
          mkdir pbrp
          cd twrp
          git config --global user.name "VThang51"
          git config --global user.email "vietthang0511.2@gmail.com"
          
      - name: Sync Minimal Manifest
        run: |
          cd pbrp
          repo init --depth=1 -u https://github.com/PitchBlackRecoveryProject/manifest_pb.git -b ${{ inputs.MANIFEST_BRANCH }}
          
      - name: Sync Source
        run: |
          cd pbrp
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
          rm -rf .rep
      
      - name: Clone Device Tree
        run: |
          cd pbrp
          git clone -b ${{ inputs.DEVICE_TREE_BRANCH }} ${{ inputs.DEVICE_TREE_URL }} device/${{ inputs.BRAND }}/${{ inputs.DEVICE_CODE }}
      - name: Compile Custom Recovery 
        run: |
          cd pbrp
          chmod 777 build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          ${{ inputs.ADD_EXPORT }}
          . build/envsetup.sh
          lunch ${{ inputs.MAKEFILE_TYPE }}_${{ inputs.DEVICE_CODE }}-eng
          mka ${{ inputs.BUILD_TARGET }}image
      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Custom Recovery for ${{ inputs.DEVICE_CODE }}
          tag_name: PBRP
          body: |
            Device: ${{ inputs.DEVICE_CODE }}
            Type: PitchBlack Recovery Project
            Target: ${{ inputs.BUILD_TARGET }}
          files: pbrp/out/target/product/${{ inputs.DEVICE_CODE }}/${{ inputs.BUILD_TARGET }}.img
