name: TWRP Builder
on:
  workflow_dispatch:
    inputs:
      GH_USERNAME:
        description: 'GitHub Username'
        description: 'test'
        required: true
      GH_EMAIL:
        description: 'GitHub Email'
        required: true
      MANIFEST_URL:
        description: 'Manifest URL'
        required: true
        default: 'aosp'
        type: choice
        options:
          - omni
          - aosp
          - lineageos
      MANIFEST_BRANCH:
        description: 'Manifest Branch'
        required: true
        default: '12.1'
        type: choice
        options:
          - twrp-4.4-deprecated
          - twrp-5.1
          - twrp-6.0
          - twrp-7.1
          - twrp-8.1
          - twrp-9.0
          - twrp-10.0-deprecated
          - twrp-11
          - twrp-12.1
          - twrp-14.1
      DEVICE_TREE_URL:
        description: 'Device Tree URL'
        required: true
        default: 'https://github.com/TeamWin/android_device_asus_I003D'
      DEVICE_TREE_BRANCH:
        description: 'Device Tree Branch'
        required: true
        default: 'android-12.1'
      DEVICE_PATH:
        description: 'Device Path'
        required: true
        default: 'device/asus/I003D'
      DEVICE_NAME:
        description: 'Device Name'
        required: true
        default: 'I003D'
      MAKEFILE_NAME:
        description: 'Makefile Name'
        required: true
        default: 'twrp_I003D'
      BUILD_TARGET:
        description: 'Build Target'
        required: true
        default: 'recovery'
        type: choice
        options:
          - recovery
          - boot
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Prepare the environment
      run: |
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
        docker rmi `docker images -q`
        sudo apt-get remove account-plugin-facebook account-plugin-flickr account-plugin-jabber account-plugin-salut account-plugin-twitter account-plugin-windows-live account-plugin-yahoo aisleriot brltty duplicity empathy empathy-common example-content gnome-accessibility-themes gnome-contacts gnome-mahjongg gnome-mines gnome-orca gnome-screensaver gnome-sudoku gnome-video-effects gnomine landscape-common libreoffice-avmedia-backend-gstreamer libreoffice-base-core libreoffice-calc libreoffice-common libreoffice-core libreoffice-draw libreoffice-gnome libreoffice-gtk libreoffice-impress libreoffice-math libreoffice-ogltrans libreoffice-pdfimport libreoffice-style-galaxy libreoffice-style-human libreoffice-writer libsane libsane-common mcp-account-manager-uoa python3-uno rhythmbox rhythmbox-plugins rhythmbox-plugin-zeitgeist sane-utils shotwell shotwell-common telepathy-gabble telepathy-haze telepathy-idle telepathy-indicator telepathy-logger telepathy-mission-control-5 telepathy-salut totem totem-common totem-plugins printer-driver-brlaser printer-driver-foo2zjs printer-driver-foo2zjs-common printer-driver-m2300w printer-driver-ptouch printer-driver-splix
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python3 python2.7 python-pip gcc clang libssl-dev repo rsync flex curl bison aria2
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Repo Sync
      run: |
        mkdir twrp
        cd twrp
        git config --global user.name "${{ inputs.GH_USERNAME }}"
        git config --global user.email "${{ inputs.GH_EMAIL }}"
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_${{ inputs.MANIFEST_URL }}.git -b ${{ inputs.MANIFEST_BRANCH }}
        repo sync -c -j4 --force-sync --no-clone-bundle --no-tags
        rm -rf .rep
      
    - name: Clone device tree
      run: |
        git clone ${{ inputs.DEVICE_TREE_URL }} -b ${{ inputs.DEVICE_TREE_BRANCH }} ${{ inputs.DEVICE_PATH }}

    - name: Building recovery
      run: |
          . build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          lunch ${{ inputs.MAKEFILE_NAME }}-eng
          mka ${{ inputs.BUILD_TARGET }}image -j128

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ inputs.DEVICE_NAME }}
        files: twrp/out/target/product/${{ inputs.DEVICE_NAME }}/${{ inputs.BUILD_TARGET }}.img
        tag_name: ${{ github.run_id }}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
