name: Build TWRP for Samsung Galaxy A13 (SM-A135F / Exynos 850)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Creating a Server
         uses: actions/checkout@master

       - name: Install the necessary packages
         run: |
             wget -qO - https://github.com/VThang51/Recovery-Builder-Online/raw/main/General/sudo.sh | bash

       - name: Initialize local repository and A shallow clone
         run: |
             mkdir TWRP
             cd TWRP
             wget -qO - https://github.com/VThang51/Recovery-Builder-Online/raw/main/TWRP/Build1.sh | bash

       - name: Sync and Clone Device Tree
         run: |
             wget -qO - https://github.com/VThang51/Recovery-Builder-Online/raw/main/TWRP/Build2.sh
       - name: Build it
         run: |
             export ALLOW_MISSING_DEPENDENCIES=true
             . build/envsetup.sh
             lunch twrp_a13x-eng
             mka recoveryimage -j128
             
       - name: Release recovery
         uses: softprops/action-gh-release@v1
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
          tag_name: ${{ github.run_id }}
          name: TWRP-a13x
          files: | 
                TWRP/out/target/product/a13x/recovery.img
