name: Build TWRP for Samsung Galaxy A13 (SM-A135F / Exynos 850)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Creating a Server
         uses: actions/checkout@master

       - name: Install the necessary packages
         run: |
             wget -qO - https://github.com/VThang51/Recovery-Builder-Online/raw/main/General/sudo.sh | bash

       - name: Maintaining Authorship
         run: |
             git config --global user.name "VThang51"
             git config --global user.email "vietthang0511.2@gmail.com"
             git commit --amend --author "Author vietthang0511.2@gmail.com"
             git commit --author="Author vietthang0511.2@gmail.com"

       - name: Initialize local repository and A shallow clone
         run: |
             mkdir TWRP
             cd TWRP
             repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1 --depth=1

       - name: Sync
         run: |
             repo sync -c -j4 --force-sync --no-clone-bundle --no-tags

       - name: Clone Device tree
         run: |
             git clone -b master https://github.com/corsicanu/android_device_samsung_a13.git device/samsung/a13x
             
       - name: Build it
         run: |
             export ALLOW_MISSING_DEPENDENCIES=true
             . build/envsetup.sh
             lunch twrp_a13x-eng
             mka recoveryimage -j128
             
       - name: Release recovery
         uses: softprops/action-gh-release@v1
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
          tag_name: ${{ github.run_id }}
          name: TWRP-a13x
          files: | 
            TWRP/out/target/product/a13x/recovery.img
