name: TWRP Builder
on:
  workflow_dispatch:
    inputs:
      GH_USERNAME:
        description: 'GitHub Username'
        required: true
        default: 'VThang51'
      GH_EMAIL:
        description: 'GitHub Email'
        required: true
        default: 'vietthang0511.2@gmail.com'
      MANIFEST_URL:
        description: 'Manifest'
        required: true
        default: 'aosp'
        type: choice
        options:
        - omni
        - aosp
        - lineageos
      MANIFEST_BRANCH:
        description: 'Manifest Branch'
        required: true
        default: 'twrp-12.1'
        type: choice
        options:
        - twrp-4.4-deprecated
        - twrp-5.1
        - twrp-6.0
        - twrp-7.1
        - twrp-8.1
        - twrp-9.0
        - twrp-10.0-deprecated
        - twrp-11
        - twrp-12.1
        - twrp-14.1
      DEVICE_TREE_URL:
        description: 'Device Tree URL'
        required: true
        default: 'https://github.com/VThang51/android_device_samsung_a13'
      DEVICE_TREE_BRANCH:
        description: 'Device Tree Branch'
        required: true
        default: 'master'
      DEVICE_PATH:
        description: 'Device Path'
        required: true
        default: 'device/samsung/a13x'
      DEVICE_NAME:
        description: 'Device Name'
        required: true
        default: 'a13x'
      MAKEFILE_NAME:
        description: 'Makefile Name'
        required: true
        default: 'twrp_a13x'
      BUILD_TARGET:
        description: 'Build Target'
        required: true
        default: 'recovery'
        type: choice
        options:
          - recovery
          - boot
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Cleanup
        run: |
          curl -LO https://github.com/VThang51/Recovery-Builder-Online/raw/main/General/Cleanup.sh | bash
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Prepare the environment
        run: |
          sudo apt-get -y update
          sudo apt-get -y upgrade
          sudo apt-get -y install bc build-essential zip curl libstdc++6 git wget python python2 gcc clang libssl-dev rsync flex curl bison aria2
          mkdir ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          sudo ln -sf ~/bin/repo /usr/bin/repo

      - name: Repo Sync
        run: |
          mkdir ~/twrp
          cd ~/twrp
          git config --global user.name "${{ inputs.GH_USERNAME }}"
          git config --global user.email "${{ inputs.GH_EMAIL }}"
          repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_${{ inputs.MANIFEST_URL }}.git -b ${{ inputs.MANIFEST_BRANCH }}
          repo sync
      
      - name: Clone device tree
        run: |
          cd ~/twrp
          git clone ${{ inputs.DEVICE_TREE_URL }} -b ${{ inputs.DEVICE_TREE_BRANCH }} ${{ inputs.DEVICE_PATH }}

      - name: Building recovery
        run: |
          cd ~/twrp
          chmod 777 build/envsetup.sh
          ./build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          lunch ${{ inputs.MAKEFILE_NAME }}-eng
          mka ${{ inputs.BUILD_TARGET }}image -j128

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ inputs.DEVICE_NAME }}
          tag_name: ${{ github.run_id }}
          body: |
            Manifest: ${{ github.event.inputs.MANIFEST_BRANCH }}
            Device: ${{ github.event.inputs.DEVICE_NAME }}
            Target: ${{ github.event.inputs.BUILD_TARGET }}.img
          files: twrp/out/target/product/${{ inputs.DEVICE_NAME }}/${{ inputs.BUILD_TARGET }}.img
