name: TWRP Builder
on:
  workflow_dispatch:
    inputs:
      MANIFEST_TYPE:
        description: 'Manifest Type'
        required: true
        default: 'AOSP'
        type: choice
        options:
        - 'Omni'
        value: omni
        - 'AOSP'
        value: aosp
        - 'LineageOS'
        value: lineageos
      MANIFEST_BRANCH:
        description: 'Manifest Branch'
        required: true
        default: 'Android 12.1 (AOSP)'
        type: choice
        options:
        - 'Android 4.4 (Deprecated-Omni)'
        value: twrp-4.4-deprecated
        - 'Android 5.1 (Omni)'
        value: twrp-5.1
        - 'Android 6.0 (Omni)'
        value: twrp-6.0
        - 'Android 7.1 (Omni)'
        value: twrp-7.1
        - 'Android 8.1 (Omni)'
        value: twrp-8.1
        - 'Android 9.0 (Omni)'
        value: twrp-9.0
        - 'Android 10.0 (Deprecated-Omni)'
        value: twrp-10.0-deprecated
        - 'Android 11 (AOSP)'
        value: twrp-11
        - 'Android 12.1 (AOSP)'
        value: twrp-12.1
        - 'LineageOS 14.1'
        value: twrp-14.1
      DEVICE_TREE_URL:
        description: 'Device Tree URL'
        required: true
        default: 'https://github.com/VThang51/android_device_samsung_a13'
      DEVICE_TREE_BRANCH:
        description: 'Device Tree Branch'
        required: true
        default: 'master'
      BRAND:
        description: 'Brand'
        required: true
        default: 'samsung'
      DEVICE_CODE:
        description: 'Device Code'
        required: true
        default: 'a13x'
      MAKEFILE_TYPE:
        description: 'Makefile Type'
        required: true
        default: 'twrp'
        type: choice
        options:
          - 'omni'
          - 'twrp'
      ADD_EXPORT:
        description: 'Add "export"'
        required: false
      BUILD_TARGET:
        description: 'Build Target'
        required: true
        default: 'Recovery Partition'
        type: choice
        options:
          - 'Recovery Partition'
          value: recovery
          - 'Boot Image Ramdisk'
          value: boot
          - 'Vendor-Boot Image Ramdisk'
          value: vendorboot
jobs:
  TeamWin-Recovery-Project:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Free up space
        uses: rokibhasansagar/slimhub_actions@main

      - name: Remove and Install the necessary Packages
        run: bash sh/sudo.sh

      - name: Sync Source and Minimal Manifest
        run: |
          mkdir ~/twrp
          cd ~/twrp
          git config --global user.name "VThang51"
          git config --global user.email "vietthang0511.2@gmail.com"
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_${{ inputs.MANIFEST_TYPE }}.git -b ${{ inputs.MANIFEST_BRANCH }}
          repo sync -c -j4 --force-sync --no-clone-bundle --no-tags
          rm -rf .rep
      
      - name: Clone Device Tree
        run: |
          cd ~/twrp
          git clone -b ${{ inputs.DEVICE_TREE_BRANCH }} ${{ inputs.DEVICE_TREE_URL }} device/${{ inputs.BRAND }}/${{ inputs.DEVICE_CODE }}

      - name: Compile Custom Recovery 
        run: |
          cd ~/twrp
          chmod 777 build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          ${{ inputs.ADD_EXPORT }}
          . build/envsetup.sh
          lunch ${{ inputs.MAKEFILE_TYPE }}_${{ inputs.DEVICE_CODE }}-eng
          mka ${{ inputs.BUILD_TARGET }}image
      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Custom Recovery for ${{ inputs.DEVICE_CODE }}
          tag_name: ${{ inputs.MANIFEST_BRANCH }}
          body: |
            Device: ${{ inputs.DEVICE_CODE }}
            Type: TeamWin Recovery Project (TWRP)
            Target: ${{ inputs.BUILD_TARGET }}
          files: twrp/out/target/product/${{ inputs.DEVICE_CODE }}/${{ inputs.BUILD_TARGET }}.img
