name: TeamWin-RP Builder 
on: 
   workflow_dispatch: 
     inputs: 
       MANIFEST_TYPE: 
         description: 'Manifest Type' 
         required: true 
         default: 'aosp' 
         type: choice 
         options: 
           - 'omni' 
           - 'aosp' 
           - 'lineageos' 
       MANIFEST_BRANCH: 
         description: 'Manifest Branch' 
         required: true 
         default: 'twrp-11' 
         type: choice 
         options: 
           - 'twrp-4.4-deprecated' 
           - 'twrp-5.1' 
           - 'twrp-6.0' 
           - 'twrp-7.1' 
           - 'twrp-8.1' 
           - 'twrp-9.0' 
           - 'twrp-10.0-deprecated' 
           - 'twrp-11' 
           - 'twrp-12.1' 
           - 'twrp-14.1' 
       DEVICE_TREE_URL: 
         description: 'Device Tree URL' 
         required: true 
         default: 'https://github.com/Akash-Dhoni-Krishnan/twrp_device_xiaomi_merlin.git' 
       DEVICE_TREE_BRANCH: 
         description: 'Device Tree Branch' 
         required: true 
         default: 'merlinx-11.0' 
       BRAND: 
         description: 'Brand' 
         required: true 
         default: 'xiaomi' 
       DEVICE_CODE: 
         description: 'Device Code' 
         required: true 
         default: 'merlinx' 
       KERNEL_URL:
         description: 'Kernel Source Code'
         required: false
       KERNEL_BRANCH:
         description: 'Kernel Source branch'
         required: false
       KERNEL_VARIANT:
         required: false
       KERNEL_VERSION:
         required: false
       MAKEFILE_TYPE: 
         description: 'Makefile Type' 
         required: true 
         default: 'twrp' 
         type: choice 
         options: 
           - 'omni' 
           - 'twrp' 
       ADD_EXPORT: 
         description: 'Add "export"' 
         required: false 
       BUILD_TARGET:
         description: 'Build Target'
         required: true
         default: 'recovery'
         type: choice
         options:
          - 'recovery'
          - 'boot'
          - 'vendorboot'
jobs:
  TeamWin-Recovery-Project:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Free up space
        run: bash sh/RP/unin.sh

      - name: Set up the Compilation environment
        run: bash sh/RP/sudo.sh

      - name: Git Config
        run: |
          rm -rf ~/twrp
          mkdir ~/twrp
          cd ~/twrp
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          
      - name: Sync Minimal Manifest
        run: |
          cd ~/twrp
          repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_${{ inputs.MANIFEST_TYPE }}.git -b ${{ inputs.MANIFEST_BRANCH }}
          
      - name: Sync Source
        run: |
          cd ~/twrp
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
          rm -rf .rep
      
      - name: Clone Device Tree
        run: |
          cd ~/twrp
          git clone -b ${{ inputs.DEVICE_TREE_BRANCH }} ${{ inputs.DEVICE_TREE_URL }} device/${{ inputs.BRAND }}/${{ inputs.DEVICE_CODE }}

      - name: Clone Kernel Source 
        run: |
          cd ~/twrp 
          git clone -b ${{ inputs.KERNEL_BRANCH }} ${{ inputs.KERNEL_URL }} kernel/${{ inputs.DEVICE_CODE }}
 
      - name: Compile Kernel
        run: |
          cd ~/twrp/kernel/${{ inputs.DEVICE_CODE }} 
          export ARCH=arm64 
          export SUBARCH=arm64 
          export CROSS_COMPILE=aarch64-linux-gnu- 
          make O=output/${{ inputs.DEVICE_CODE }}-${{ inputs.KERNEL_VERSION }}-${{ inputs.KERNEL_VARIANT }} ${KERNEL_DEFCONFIG}
          make -j$(nproc --all) O=output/${{ inputs.DEVICE_CODE }}-${{ inputs.KERNEL_VERSION }}-${{ inputs.KERNEL_VARIANT }}
 
      - name: Copy Kernel Image 
        run: |
          cd ~/twrp/kernel/${{ inputs.DEVICE_CODE }}/output/${{ inputs.DEVICE_CODE }}-${{ inputs.KERNEL_VERSION }}-${{ inputs.KERNEL_VARIANT }} 
          cp arch/arm64/boot/Image.gz-dtb ~/twrp/device/${{ inputs.BRAND }}/${{ inputs.DEVICE_CODE }}/kernel
 
      - name: Compile Custom Recovery  
         run: |
           sudo apt-get update 
           sudo apt-get -y install f2fs-tools 
           cd ~/twrp 
           chmod 777 build/envsetup.sh 
           export ALLOW_MISSING_DEPENDENCIES=true 
           ${{ inputs.ADD_EXPORT }} 
           . build/envsetup.sh 
           lunch ${{ inputs.MAKEFILE_TYPE }}_${{ inputs.DEVICE_CODE }}-eng 
           mka recoveryimage target_link_libraries+=-lf2fs 
         continue-on-error: true
 
       - name: Rename File 
         run: | 
           mv ~/twrp/out/target/product/${{ inputs.DEVICE_CODE }}/${{ inputs.BUILD_TARGET }}.img unofficialtwrp-${{ inputs.DEVICE_CODE }}.img 
 
       - name: Upload to Release 
         uses: softprops/action-gh-release@v1 
         env: 
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
         with: 
           name: Custom Recovery for ${{ inputs.DEVICE_CODE }} 
           tag_name: TWRP 
           body: | 
             Device: ${{ inputs.DEVICE_CODE }} 
             Type: TeamWin Recovery Project 
             Target: ${{ inputs.BUILD_TARGET }} 
           files: unofficialtwrp-${{ inputs.DEVICE_CODE }}.img
